spring:
  application:
    name: gateway-service

server:
  port: 8080

  cloud:
    gateway:
      routes: []  # ??? ?? ??

eureka:
  client:
    register-with-eureka: false  # Eureka? ?? ???? false
    fetch-registry: false
  instance:
   hostname: localhost